---
title: "Apparent Cement Consumption in Spain: Historical Data"
author: "Enrique Pérez Herrero"
date: "January 18, 2017"
output: 
  html_document: 
    fig_width: 9
    highlight: tango
    number_sections: yes
    theme: cosmo
    toc: yes
---


# Summary

Resumen: 

# Load Packages 

```{r, warning=FALSE, message=FALSE}
library(xml2)
library(rvest)
library(dygraphs)
library(xts)
```


# Data Source

```{r}
data_url <- paste0("http://tematicas.org/",
                   "sintesis-economica/",
                   "indicadores-de-produccion-y-demanda-nacional/",
                   "consumo-aparente-de-cemento/")
```


# Reading HTML page

```{r}
data_page <- data_url %>%
  read_html
```


# Extracting info and tidying data

## Title

```{r}
title <- data_page %>%
  html_node(xpath = "//h1") %>%
  html_text

cat(title)
```

## Notes

```{r}
notes <- data_page %>%
  html_node(xpath = "//*[@itemprop='description']") %>%
  html_text %>%
  gsub("\\.(\\D)", ".\n\\1", .)

cat(notes)
```


## Table data

```{r}
table_cement <- data_page %>%
  html_table %>%
  data.frame %>%
  .[, -c(1)]

names(table_cement) <- c("Date", "kt")

# Convert data to numeric
table_cement$kt <- table_cement$kt %>%
  gsub(",", "", .) %>%
  as.numeric

# Change locale for spanish date conversion

my_LC_TIME <- Sys.getlocale("LC_TIME")
Sys.setlocale("LC_TIME", "es_ES.UTF-8")

# Convert Date

table_cement$Date <- table_cement$Date %>%
  tolower %>%
  gsub("^([a-z]{3}).+([0-9]{4})$", "\\1-\\2", .) %>%
  paste0("1-", .) %>%
  as.Date(. , "%d-%b-%Y")

# Back up locale
Sys.setlocale("LC_TIME", my_LC_TIME)

# Sort by date
table_cement <- table_cement[order(table_cement$Date), ]

head(table_cement)
```


## Extracting Start and End dates

```{r}
start_year <- table_cement$Date %>%
  min %>%
  format(., "%Y") %>%
  as.numeric

start_month <- table_cement$Date %>%
  min %>%
  format(., "%m") %>%
  as.numeric

end_year <- table_cement$Date %>%
  max %>%
  format(., "%Y") %>%
  as.numeric

end_month <- table_cement$Date %>%
  max %>%
  format(., "%m") %>%
  as.numeric
```


# Converting to Time Series

```{r}
ts_cement <- ts(table_cement$kt,
        start = c(start_year, start_month),
        end = c(end_year, end_month),
        deltat = 1/12)

xts_cement <- as.xts(ts_cement)
```


# Saving xts as csv file

```{r}
xts_file_path <- "data/xts_cement.csv"

write.zoo(xts_cement, file = xts_file_path, sep = ",")
```

# Plotting Apparent Cement Consumption

```{r}
dygraph(xts_cement, main = title) %>%
  dySeries("V1", label = "miles Tm") %>%
  dyOptions(fillGraph = TRUE) %>%
  dyRangeSelector()
```


# Links
* [TEMÁTICAS: Indicadores de Producción y Demanda Nacional, Consumo aparente de cemento](http://tematicas.org/sintesis-economica/indicadores-de-produccion-y-demanda-nacional/consumo-aparente-de-cemento/)